!function(){var k={};k.g=function(){if("object"==typeof globalThis)return globalThis;try{return this||(new Function("return this"))()}catch(f){if("object"==typeof window)return window}}();k.r=function(f){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(f,Symbol.toStringTag,{value:"Module"});Object.defineProperty(f,"__esModule",{value:!0})};var p={};!function(){function f(a){return!(1<a.parentElement.querySelectorAll(".c-110-promo-box").length)}function q(a){var b=a.currentStyle||
window.getComputedStyle(a);return a.offsetHeight+(parseInt(b.marginTop,10)||0)+(parseInt(b.marginBottom,10)||0)}function r(){651>window.innerWidth||e.forEach(function(a){a=[].slice.call(a.querySelectorAll(".c-110-promo-box"));if(1<a.length){var b=a.map(function(c){return q(c)}).reduce(function(c,d){return c>d?c:d},-1/0);a.forEach(function(c){q(c)&&(c.style.height="".concat(b,"px"))})}})}function t(){(u+=1)===n.length&&r()}function v(){1<n.length?(u=0,[].forEach.call(n,function(a){a.complete?t():a.addEventListener("load",
t,!1)})):r()}function w(){651>window.innerWidth||e.forEach(function(a){a=[].slice.call(a.querySelectorAll(".c-110-promo-box .persona  .content \x3e .heading"));if(1<a.length){var b=a.map(function(c){return c.offsetHeight}).reduce(function(c,d){return c>d?c:d},-1/0);a.forEach(function(c){c.offsetHeight!==b&&(c.style.height="".concat(b,"px"))})}})}function l(){clearTimeout(x);x=setTimeout(function(){e.forEach(function(a){a=[].slice.call(a.querySelectorAll(".c-110-promo-box"));1<a.length&&a.forEach(function(b){b.style.height=
null})});v();e.forEach(function(a){a=[].slice.call(a.querySelectorAll(".c-110-promo-box .persona  .content \x3e .heading"));1<a.length&&a.forEach(function(b){b.style.height=null})});w()},300)}function y(){Array.from(document.querySelectorAll(".c-110-promo-box")).filter(A).filter(f).forEach(function(a){var b=a.parentElement.parentElement;b.classList.contains("row")&&0>=e.filter(function(c){return c===b}).length&&e.push(b)});v();w();g()}var u=0,x=!1,e=[],n=document.querySelectorAll(".c-110-promo-box .promo-box-image-container img"),
A=function(a){a=a.parentElement;return!(null==a?0:a.classList.contains("col-md-12"))},m=function(){document.querySelectorAll(".promo-box-v3.vertical.video").forEach(function(a){var b=a.querySelector(".promo-box-image-container \x3e img").getBoundingClientRect().height,c=a.querySelector(".promo-box-image-container \x3e img").getBoundingClientRect().width;a.querySelector(".video-component-placeholder").style.height="".concat(b,"px");a.querySelector(".video-component-placeholder").style.width="".concat(c,
"px")});document.querySelectorAll(".promo-box-v3.horizontal.video").forEach(function(a){var b=a.querySelector(".image-container \x3e .full-bleed-bg").getBoundingClientRect().height,c=a.querySelector(".image-container \x3e .full-bleed-bg").getBoundingClientRect().width;a.querySelector(".video-component-placeholder").style.height="".concat(b,"px");a.querySelector(".video-component-placeholder").style.width="".concat(c,"px")})},g=function(){var a=document.querySelectorAll(".brochureware");1<a.length&&
a.forEach(function(b){var c=b.getAttribute("data-image-desktop"),d=b.getAttribute("data-image-mobile");651<k.g.window.innerWidth?b.style.backgroundImage="url('".concat(c,"')"):b.style.backgroundImage="url('".concat(d,"')")});a=document.querySelectorAll(".promo-box-v3 .load-background-image");a.length&&a.forEach(function(b){767<window.innerWidth?b.style.backgroundImage="url('".concat(b.attributes["data-image-desktop"].value,"')"):651<window.innerWidth?b.style.backgroundImage="url('".concat(b.attributes["data-image-tablet"].value,
"')"):b.style.backgroundImage="none"})},z=function(){var a=document.querySelectorAll(".promo-box-shadow");1025<window.innerWidth&&a.forEach(function(b){if(b.classList.contains("promo-box")&&b.addEventListener("click",function(){var h=b.querySelector(".btn");h&&h.click()}),b.classList.contains("promo-box-v3")&&!b.classList.contains("brochureware")&&b.addEventListener("click",function(){var h=b.querySelector(".content + .btn");h&&h.click()}),b.classList.contains("promo-box-v3")&&b.classList.contains("brochureware")){var c=
b.querySelectorAll(".btn"),d=c[c.length-1];d&&(d.classList.add("container-link"),b.addEventListener("click",function(){d.click()}))}})};document.querySelectorAll(".accordion-list-item-link").forEach(function(a){a.addEventListener("click",function(){setTimeout(function(){l();m();g()},10)})});window.addEventListener("load",function(){y();l();m();g();z()});window.addEventListener("resize",function(){l();m();g()});"complete"===document.readyState&&(y(),l(),m(),g(),z())}();k.r(p);window["c-110-promo-box"]=
p}();